// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

<<<<<<<< HEAD:codex-rs/app-server-protocol/schema/typescript/v2/ExternalAgentConfigImportResponse.ts
export type ExternalAgentConfigImportResponse = Record<string, never>;
========
export type ImageDetail = "auto" | "low" | "high" | "original";
>>>>>>>> upstream_main:codex-rs/app-server-protocol/schema/typescript/ImageDetail.ts
