// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
<<<<<<< HEAD
=======
import type { RealtimeConversationVersion } from "../RealtimeConversationVersion";
>>>>>>> upstream_main

/**
 * EXPERIMENTAL - emitted when thread realtime startup is accepted.
 */
<<<<<<< HEAD
export type ThreadRealtimeStartedNotification = { threadId: string, sessionId: string | null, };
=======
export type ThreadRealtimeStartedNotification = { threadId: string, sessionId: string | null, version: RealtimeConversationVersion, };
>>>>>>> upstream_main
