// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

<<<<<<<< HEAD:codex-rs/app-server-protocol/schema/typescript/v2/ModelAvailabilityNux.ts
export type ModelAvailabilityNux = { message: string, };
========
export type AgentPath = string;
>>>>>>>> upstream_main:codex-rs/app-server-protocol/schema/typescript/AgentPath.ts
