// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

<<<<<<<< HEAD:codex-rs/app-server-protocol/schema/typescript/v2/DynamicToolCallStatus.ts
export type DynamicToolCallStatus = "inProgress" | "completed" | "failed";
========
export type FuzzyFileSearchMatchType = "file" | "directory";
>>>>>>>> upstream_main:codex-rs/app-server-protocol/schema/typescript/FuzzyFileSearchMatchType.ts
