// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "./AbsolutePathBuf";

<<<<<<< HEAD:codex-rs/app-server-protocol/schema/typescript/FileSystemPermissions.ts
export type FileSystemPermissions = { read: Array<AbsolutePathBuf> | null, write: Array<AbsolutePathBuf> | null, };
=======
export type MacOsAutomationPermission = "none" | "all" | { "bundle_ids": Array<string> };
>>>>>>> upstream_main:codex-rs/app-server-protocol/schema/typescript/MacOsAutomationPermission.ts
