name: Alert sync issues
on:
  schedule:
    - cron: '17 * * * *'
  workflow_dispatch:

jobs:
  sync:
    uses: KooshaPari/phenoShared/.github/workflows/reusable/alert-sync-issues.yml@{"message":"Not Found","documentation_url":"https://docs.github.com/rest/commits/commits#get-a-commit","status":"404"}
    with:
      auto-label: auto-alert-sync
